# Generated by Django 3.1.7 on 2021-03-02 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descripion',
            new_name='description',
        ),
    ]
